spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations:
            - classpath:config/telemetry/{application}
            - classpath:config/commerce/{application}
      discovery:
        enabled: true
        serviceId: config-server

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname:localhost}:${eureka.instance.port:8761}/eureka/
  instance:
    instanceId: ${spring.application.name}:${random.value}
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10 # Heartbeats каждые 10 секунд
    leaseExpirationDurationInSeconds: 30 # Истечение через 30 секунд

server:
  port: 0