spring:
  application:
    name: collector

server:
  port: 8080

logging:
  level:
    ru.yandex.practicum.telemetry: TRACE
    org:
      springframework: ERROR
      apache.kafka: WARN

collector:
  kafka:
    producer:
      properties:
        bootstrap.servers: localhost:9092
        client.id: collector
        key.serializer: org.apache.kafka.common.serialization.StringSerializer
        value.serializer: ru.yandex.practicum.kafka.collector.serializer.AvroSerializer
      topics:
        sensors-events: "telemetry.sensors.v1"
        hubs-events: "telemetry.hubs.v1"