spring:
  main:
    web-application-type: none

logging:
  level:
    ru.yandex.practicum.telemetry: TRACE
    org:
      springframework: ERROR
      apache.kafka: WARN

aggregator:
  kafka:
    consumer:
      properties:
        bootstrap.servers: localhost:9092
        group.id: aggregator-group
        auto.offset.reset: earliest
        enable.auto.commit: false
        key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value.deserializer: ru.yandex.practicum.aggregator.serialization.deserializer.SensorEventDeserializer
      topic: telemetry.sensors.v1
    producer:
      properties:
        bootstrap.servers: localhost:9092
        key.serializer: org.apache.kafka.common.serialization.StringSerializer
        value.serializer: ru.yandex.practicum.aggregator.serialization.serializer.AvroSerializer
      topic: telemetry.snapshots.v1