spring:
  application:
    name: warehouse
  config:
    import: "configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: config-server
      retry:
        useRandomPolicy: true
        max-interval: 6000

eureka:
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname:localhost}:${eureka.instance.port:8761}/eureka/
    registryFetchIntervalSeconds: 5 # Уменьшаем интервал обновления кэша до 5 секунд