CREATE TABLE warehouse_products (
    id UUID PRIMARY KEY,
    width DOUBLE PRECISION NOT NULL,
    height DOUBLE PRECISION NOT NULL,
    depth DOUBLE PRECISION NOT NULL,
    weight DOUBLE PRECISION NOT NULL,
    is_fragile BOOLEAN NOT NULL,
    quantity BIGINT NOT NULL
);